FROM condaforge/miniforge3

RUN apt update && apt install -y \
    nano \
    cmake \
    git \
    g++ \
    libpcl-dev \
    pybind11-dev \
    && rm -rf /var/lib/apt/lists/*


RUN conda install pip

# --- Install Open3D ---
ARG OPEN3D_VERSION="0.19.0"
RUN apt update && apt install -y sudo && \
    git clone -b v${OPEN3D_VERSION} https://github.com/isl-org/Open3D.git /opt/Open3D && \
    cd /opt/Open3D && ./util/install_deps_ubuntu.sh assume-yes && \
    mkdir build && cd build && \
    cmake .. -DBUILD_PYTHON_MODULE=ON && \
    make -j$(($(nproc) / 2 < 1 ? 1 : $(nproc) / 2)) && \
    make install && \
    rm -rf /opt/Open3D

# SHELL [ "/bin/bash" ]
    
WORKDIR /root

RUN git clone --recurse-submodules https://github.com/Y-Ride/ELite.git \
    && cd ELite \
    && . ~/.bashrc \
    && pip install -e .

WORKDIR /root/ELite

RUN . ~/.bashrc && \
    cd external/fast_gicp \
    && python3 setup.py install

# Uncomment the bash_completion lines in the .bashrc file
RUN sed -i '/#if \[ -f \/etc\/bash_completion \]/s/^#//' ~/.bashrc && \
    sed -i '/#    \. \/etc\/bash_completion/s/^#//' ~/.bashrc && \
    sed -i '/#fi$/s/^#//' ~/.bashrc

# Insert the custom_env.sh block right before the 'enable programmable completion' block.
# We'll search for the line starting with '# enable programmable completion features'
# and insert the new block before it.
RUN sed -i '/# enable programmable completion features/i\
if [ -f /yride_env_setup/custom_env.sh ]; then\n\
  source /yride_env_setup/custom_env.sh\n\
fi\n' ~/.bashrc