FROM condaforge/miniforge3

RUN apt update && apt install -y \
    nano \
    cmake \
    git \
    g++ \
    libpcl-dev \
    pybind11-dev \
    && rm -rf /var/lib/apt/lists/*


RUN conda install pip

# --- Install Open3D ---
ARG OPEN3D_VERSION="0.19.0"
RUN apt update && apt install -y sudo && \
    git clone -b v${OPEN3D_VERSION} https://github.com/isl-org/Open3D.git /opt/Open3D && \
    cd /opt/Open3D && ./util/install_deps_ubuntu.sh assume-yes && \
    mkdir build && cd build && \
    cmake .. -DBUILD_PYTHON_MODULE=ON && \
    make -j$(($(nproc) / 2 < 1 ? 1 : $(nproc) / 2)) && \
    make install && \
    rm -rf /opt/Open3D
    
WORKDIR /root

RUN git clone https://github.com/Y-Ride/ELite.git \
    && cd ELite 
    # && pip install -e .

WORKDIR /root/ELite

# RUN cd external/fast_gicp \
#     && python3 setup.py install

# Include the custom environment setup script
RUN echo "if [ -f /yride_env_setup/custom_env.sh ]; then" >> ~/.bashrc && \
    echo "  source /yride_env_setup/custom_env.sh" >> ~/.bashrc && \
    echo "fi" >> ~/.bashrc