FROM condaforge/miniforge3

RUN apt update && apt install -y \
    nano \
    cmake \
    git \
    g++ \
    libpcl-dev \
    pybind11-dev \
    && rm -rf /var/lib/apt/lists/*


RUN conda install pip

WORKDIR /root

RUN git clone https://github.com/Y-Ride/ELite.git \
    && cd ELite \
    && pip install -e .

WORKDIR /root/ELite

# RUN cd external/fast_gicp \
#     && python3 setup.py install